# kots host
Vagrant.configure("2") do |config|
  config.vm.define "kots" do |kots|
    kots.vm.box = "hashicorp/bionic64"
    kots.vm.box_check_update = false
    kots.vm.network "forwarded_port", guest: 80, host: 8080
    kots.vm.network "private_network", ip: "192.168.64.100"
    kots.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "2048"
      vb.name = "kots"
    end

    # post-install script
    kots.vm.provision :shell, path: "scripts/configure-hostname.sh", :args => "kots"
    kots.vm.provision :shell, path: "scripts/configure-ntp.sh", :args => "UTC"
    kots.vm.provision :shell, path: "scripts/install-terraform-aws.sh"
  end
end
