# frontend deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nodeapp-dev
  creationTimestamp: null
  labels:
    app: nodeapp
  name: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodeapp
    spec:
      containers:
      - image: dyvantage01/nodeapp:1.1.6
        name: nodeapp
        env:
          - name: NODEAPP_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: nodeapp-secrets
                key: NODEAPP_DB_PASSWORD
        ports:
        - containerPort: 81
        envFrom:
        - configMapRef:
            name: nodeapp-configmap
